/**
 * CompositionPlayer.js
 * Handles composition playback, musical events, and drawing sounds
 * Extracted from AudioService.js for Phase 2 refactoring
 */
class CompositionPlayer {
  constructor() {
    // References to synths (set by AudioService)
    this.ambientLayers = null
    this.gestureSynth = null

    // Drone loop interval for ambient compositions
    this.droneLoopInterval = null

    // Scheduled timeouts for cleanup
    this.scheduledTimeouts = []

    // Mute state
    this.muted = false

    // Duration map for Tone.js notation
    this.durationMap = {
      '32n': 0.0625,
      '16n': 0.125,
      '8n': 0.25,
      '4n': 0.5,
      '2n': 1.0,
      '1n': 2.0
    }

    // Velocity calculator reference (for articulation)
    this.velocityCalculator = window.VelocityCalculator || null

    // Entry #NEW: Current style for genre-aware velocity
    this.currentStyle = null
  }

  /**
   * Set current style for genre-aware velocity calculations
   * Entry #NEW: Called by AudioService before playComposition
   * @param {Object} style - Style from BackgroundCompositionService
   */
  setCurrentStyle(style) {
    this.currentStyle = style
  }

  /**
   * Get genre-aware velocity config for composition voices
   * Entry #NEW: Returns velocity multipliers based on dominant genre
   * Entry #180: Expanded with all genres and articulation hints
   * @param {Object} style - Style object (optional, uses this.currentStyle if not provided)
   * @returns {Object} Velocity config per voice role with articulation
   */
  getVelocityConfig(style) {
    const targetStyle = style || this.currentStyle
    const genre = targetStyle?.dominantGenre || 'ambient'

    // Entry #180: Genre-specific velocity and articulation configs
    const configs = {
      ambient: {
        velocity: { melody: 0.06, harmony: 0.04, bass: 0.05, pad: 0.03 },
        articulation: 'legato',
        noteLengthMultiplier: 1.5  // Longer notes
      },
      classical: {
        velocity: { melody: 0.10, harmony: 0.06, bass: 0.08, pad: 0.04 },
        articulation: 'legato',
        noteLengthMultiplier: 1.2
      },
      jazz: {
        velocity: { melody: 0.12, harmony: 0.08, bass: 0.10, pad: 0.05 },
        articulation: 'portato',
        noteLengthMultiplier: 0.9  // Slightly detached
      },
      melodic: {
        velocity: { melody: 0.10, harmony: 0.06, bass: 0.08, pad: 0.04 },
        articulation: 'legato',
        noteLengthMultiplier: 1.0
      },
      pop: {
        velocity: { melody: 0.11, harmony: 0.07, bass: 0.09, pad: 0.05 },
        articulation: 'normal',
        noteLengthMultiplier: 1.0
      },
      electronic: {
        velocity: { melody: 0.14, harmony: 0.10, bass: 0.12, pad: 0.06 },
        articulation: 'staccato',
        noteLengthMultiplier: 0.7  // Shorter, punchy
      },
      rhythmic: {
        velocity: { melody: 0.14, harmony: 0.10, bass: 0.12, pad: 0.06 },
        articulation: 'staccato',
        noteLengthMultiplier: 0.6  // Very short
      },
      rock: {
        velocity: { melody: 0.16, harmony: 0.12, bass: 0.14, pad: 0.07 },
        articulation: 'marcato',
        noteLengthMultiplier: 0.8
      },
      experimental: {
        velocity: { melody: 0.12, harmony: 0.08, bass: 0.10, pad: 0.05 },
        articulation: 'varied',
        noteLengthMultiplier: 1.0
      }
    }

    const config = configs[genre] || configs.ambient

    // Return velocity object for backward compatibility, with extra properties
    return {
      ...config.velocity,
      articulation: config.articulation,
      noteLengthMultiplier: config.noteLengthMultiplier
    }
  }

  /**
   * Set synth references
   * @param {Object} ambientLayers - Ambient layer synths
   * @param {Object} gestureSynth - Gesture synth
   */
  setSynths(ambientLayers, gestureSynth) {
    this.ambientLayers = ambientLayers
    this.gestureSynth = gestureSynth
  }

  /**
   * Set mute state
   * @param {boolean} muted - Mute state
   */
  setMuted(muted) {
    this.muted = muted
  }

  /**
   * Play background composition generated by CompositionEngine
   * @param {Object} composition - Composition from BackgroundCompositionService
   * @param {boolean} isDrone - Whether this is a drone composition
   */
  playComposition(composition, isDrone = false) {
    if (this.muted) {
      // console.log('🔇 playComposition blocked - muted')
      return
    }

    if (!composition || !composition.content) {
      // console.warn('🎼 Invalid composition data')
      return
    }

    const tempo = composition.metadata?.tempo || 120

    // console.log(`🎼 Playing ${composition.type} composition${isDrone ? ' (DRONE)' : ''}:`, {
//      form: composition.structure?.form,
//      section: composition.structure?.currentSection,
//      tempo: tempo,
//      key: composition.metadata?.keyCenter
//    })

    // If this is NOT a drone and we have a drone loop running, stop it
    if (!isDrone && this.droneLoopInterval) {
      // console.log('🛑 Stopping drone loop - real composition starting')
      clearInterval(this.droneLoopInterval)
      this.droneLoopInterval = null
    }

    const content = composition.content
    const type = composition.type

    try {
      if (type === 'polyphonic' && content.voices) {
        this.playPolyphonicComposition(content, tempo)
      } else if (type === 'homophonic' && content.melody) {
        this.playHomophonicComposition(content, tempo)
      } else if (type === 'ambient' && content.texture) {
        this.playAmbientComposition(content, tempo, isDrone)
      } else {
        // console.warn('🎼 Unknown composition type:', type)
      }
    } catch (error) {
      // console.error('🎼 Error playing composition:', error)
    }
  }

  /**
   * Play polyphonic composition (multiple voices)
   * @param {Object} content - Composition content with voices
   * @param {number} tempo - Tempo in BPM
   */
  playPolyphonicComposition(content, tempo = 120) {
    if (!content.voices || !Array.isArray(content.voices)) return
    if (!this.ambientLayers) return

    const beatDuration = 60 / tempo

    // Entry #NEW: Get genre-aware velocity config
    const velocityConfig = this.getVelocityConfig()

    // console.log(`🎼 Playing polyphonic: ${content.voices.length} voices at ${tempo} BPM`)

    content.voices.forEach((voice, voiceIndex) => {
      if (!voice.notes || !Array.isArray(voice.notes)) return

      const voiceRole = voice.voiceRole || 'harmony'

      // Entry #NEW: Role-based configuration with genre-aware velocities
      const roleConfig = {
        'melody': { layer: 'backgroundHigh', velocity: velocityConfig.melody, articulation: 'staccato' },
        'harmony': { layer: 'backgroundMid', velocity: velocityConfig.harmony, articulation: 'normal' },
        'bass': { layer: 'backgroundLow', velocity: velocityConfig.bass, articulation: 'legato' },
        'pad': { layer: 'backgroundLow', velocity: velocityConfig.pad, articulation: 'legato' }
      }[voiceRole] || { layer: 'backgroundMid', velocity: velocityConfig.harmony, articulation: 'normal' }

      voice.notes.forEach((note, noteIndex) => {
        const pitch = note.pitch || 60
        const frequency = this.midiToFrequency(pitch)
        const duration = note.duration || 0.5
        const delay = (note.startBeat || 0) * beatDuration

        const timeoutId = setTimeout(() => {
          if (this.ambientLayers && this.ambientLayers[roleConfig.layer]) {
            this.ambientLayers[roleConfig.layer].triggerAttackRelease(
              frequency, duration, undefined, roleConfig.velocity
            )
          }
        }, delay * 1000)

        this.scheduledTimeouts.push(timeoutId)
      })
    })
  }

  /**
   * Play homophonic composition (melody + accompaniment)
   * @param {Object} content - Composition content
   * @param {number} tempo - Tempo in BPM
   */
  playHomophonicComposition(content, tempo = 120) {
    if (!this.ambientLayers) return

    const beatDuration = 60 / tempo

    if (content.melody && content.melody.notes) {
      content.melody.notes.forEach((note, index) => {
        const pitch = note.pitch || 60
        const frequency = this.midiToFrequency(pitch)
        const duration = note.duration || 0.5
        const velocity = 0.12
        const delay = (note.startBeat || index * 0.5) * beatDuration

        const timeoutId = setTimeout(() => {
          if (this.ambientLayers && this.ambientLayers.backgroundHigh) {
            this.ambientLayers.backgroundHigh.triggerAttackRelease(
              frequency, duration, undefined, velocity
            )
          }
        }, delay * 1000)

        this.scheduledTimeouts.push(timeoutId)
      })
    }

    if (content.accompaniment) {
      this.playAccompaniment(content.accompaniment, tempo)
    }
  }

  /**
   * Play accompaniment (arpeggios, chord pads)
   * @param {Object} accompaniment - Accompaniment data
   * @param {number} tempo - Tempo in BPM
   */
  playAccompaniment(accompaniment, tempo = 120) {
    if (!this.ambientLayers) return

    const beatDuration = 60 / tempo
    const type = accompaniment.type

    if (type === 'arpeggio' && accompaniment.pattern) {
      accompaniment.pattern.forEach((chord, chordIndex) => {
        if (!chord.notes || !Array.isArray(chord.notes)) return

        chord.notes.forEach((pitch, noteIndex) => {
          const frequency = this.midiToFrequency(pitch)
          const duration = chord.rhythm || 0.25
          const delay = (chordIndex * 2 + noteIndex * 0.25) * beatDuration

          const timeoutId = setTimeout(() => {
            if (this.ambientLayers && this.ambientLayers.backgroundMid) {
              this.ambientLayers.backgroundMid.triggerAttackRelease(
                frequency, duration, undefined, 0.06
              )
            }
          }, delay * 1000)

          this.scheduledTimeouts.push(timeoutId)
        })
      })
    } else if (type === 'chord_pads' && accompaniment.chords) {
      accompaniment.chords.forEach((chord, index) => {
        const chordNotes = this.buildChordFromName(chord.chord || 'C')
        const delay = index * 4 * beatDuration

        chordNotes.forEach(pitch => {
          const frequency = this.midiToFrequency(pitch)
          const duration = chord.duration || 4

          const timeoutId = setTimeout(() => {
            if (this.ambientLayers && this.ambientLayers.backgroundLow) {
              this.ambientLayers.backgroundLow.triggerAttackRelease(
                frequency, duration, undefined, 0.05
              )
            }
          }, delay * 1000)

          this.scheduledTimeouts.push(timeoutId)
        })
      })
    }
  }

  /**
   * Play ambient composition (textural)
   * @param {Object} content - Composition content
   * @param {number} tempo - Tempo in BPM
   * @param {boolean} isDrone - Whether to loop as drone
   */
  playAmbientComposition(content, tempo = 120, isDrone = false) {
    if (!this.ambientLayers) return

    if (!content.texture || !Array.isArray(content.texture)) {
      // console.warn('🎼 No texture array in ambient composition')
      return
    }

    content.texture.forEach((textureItem, index) => {
      const delay = index * 0.5

      const timeoutId = setTimeout(() => {
        if (textureItem.note) {
          const midiNote = this.noteNameToMidi(textureItem.note)
          const frequency = this.midiToFrequency(midiNote)
          const duration = (textureItem.duration || 8000) / 1000
          const velocity = textureItem.velocity || 0.2

          const layer = isDrone ? this.ambientLayers.pad : this.ambientLayers.backgroundLow

          if (layer) {
            layer.triggerAttackRelease(frequency, duration, undefined, velocity)
          }

          // If this is a drone, schedule it to loop
          if (isDrone) {
            if (this.droneLoopInterval) {
              clearInterval(this.droneLoopInterval)
            }

            this.droneLoopInterval = setInterval(() => {
              if (this.ambientLayers && this.ambientLayers.pad) {
                this.ambientLayers.pad.triggerAttackRelease(
                  frequency, duration, undefined, velocity
                )
              }
            }, duration * 1000)
          }
        }
      }, delay * 1000)

      this.scheduledTimeouts.push(timeoutId)
    })
  }

  /**
   * Play musical event from gesture with proper articulation and duration
   * @param {Object} musicalEvent - Musical event data
   */
  playMusicalEvent(musicalEvent) {
    if (!musicalEvent || this.muted) {
      return
    }

    if (!this.gestureSynth || this.gestureSynth.disposed) {
      // console.warn('🔇 Gesture synth not available')
      return
    }

    const startTime = performance.now()

    try {
      let pitch, velocity, duration, articulation, frequency

      if (musicalEvent.properties) {
        // Backend format
        frequency = musicalEvent.properties.frequency
        duration = musicalEvent.properties.duration
        velocity = musicalEvent.properties.velocity || 50
        articulation = musicalEvent.properties.articulation || 'default'
      } else {
        // Frontend format
        pitch = musicalEvent.pitch
        velocity = musicalEvent.velocity
        duration = musicalEvent.duration
        articulation = musicalEvent.articulation

        if (pitch === undefined || velocity === undefined || duration === undefined) {
          // console.warn('🔇 Invalid musical event data')
          return
        }

        frequency = this.midiToFrequency(pitch)
      }

      // Convert duration to seconds
      let normalizedDuration = duration
      if (typeof duration === 'string') {
        normalizedDuration = this.durationMap[duration] || 0.125
      } else if (typeof duration === 'number') {
        if (duration < 10) {
          normalizedDuration = duration * 0.25
        }
        normalizedDuration = Math.max(0.05, Math.min(4.0, normalizedDuration))
      }

      // Normalize velocity
      let adjustedVelocity
      if (musicalEvent.properties) {
        adjustedVelocity = Math.max(0.1, Math.min(1.0, (velocity || 50) / 100))
      } else {
        adjustedVelocity = Math.max(0.1, Math.min(1.0, velocity / 127))
      }

      let adjustedDuration = normalizedDuration

      if (articulation === 'marcato') {
        adjustedVelocity *= 1.2
      }

      adjustedDuration = Math.max(0.02, Math.min(3.0, adjustedDuration))

      // Calculate timing
      let delay = 0
      if (musicalEvent.timestamp) {
        delay = Math.max(0, (musicalEvent.timestamp - Date.now()) / 1000)
      }

      const delayMs = delay * 1000

      const attackTimeoutId = setTimeout(() => {
        if (!this.gestureSynth || this.gestureSynth.disposed) {
          return
        }

        try {
          const isStreamed = musicalEvent.properties?.isStreamed

          // Configure envelope based on articulation
          let envelope = this.getEnvelopeForArticulation(articulation, adjustedDuration)

          if (isStreamed) {
            this.gestureSynth.set({
              oscillator: { type: 'square' },
              envelope
            })
          } else {
            this.gestureSynth.set({
              oscillator: { type: 'sawtooth' },
              envelope
            })
          }

          const finalVelocity = isStreamed ? adjustedVelocity * 0.6 : adjustedVelocity

          this.gestureSynth.triggerAttackRelease(
            frequency,
            adjustedDuration,
            typeof Tone !== 'undefined' ? Tone.now() : undefined,
            finalVelocity
          )

        } catch (e) {
          // console.warn('Note play error:', e.message)
        }
      }, delayMs)

      this.scheduledTimeouts.push(attackTimeoutId)

      // Track performance
      const latency = performance.now() - startTime
      if (latency > 50) {
        // console.warn(`🐌 High musical event latency: ${latency.toFixed(1)}ms`)
      }

    } catch (error) {
      // console.error('🔇 Error playing musical event:', error)
    }
  }

  /**
   * Get envelope parameters for articulation
   * @param {string} articulation - Articulation type
   * @param {number} duration - Note duration
   * @returns {Object} ADSR envelope
   */
  getEnvelopeForArticulation(articulation, duration) {
    // Use VelocityCalculator if available
    if (this.velocityCalculator && this.velocityCalculator.getEnvelopeFromArticulation) {
      return this.velocityCalculator.getEnvelopeFromArticulation(articulation, duration)
    }

    // Fallback implementation
    switch (articulation) {
      case 'staccato':
        return {
          attack: 0.005,
          decay: duration * 0.2,
          sustain: 0.3,
          release: duration * 0.3
        }
      case 'marcato':
        return {
          attack: 0.01,
          decay: duration * 0.3,
          sustain: 0.5,
          release: duration * 0.4
        }
      case 'legato':
        return {
          attack: duration * 0.1,
          decay: duration * 0.2,
          sustain: 0.7,
          release: duration * 0.7
        }
      default:
        return {
          attack: 0.005,
          decay: 0.02,
          sustain: 0.1,
          release: 0.05
        }
    }
  }

  /**
   * Play sound effect for remote drawing stroke
   * @param {string} color - User's assigned color (hex format)
   * @param {Function} mapColorToFrequency - Color-to-frequency mapping function
   */
  playDrawSound(color, mapColorToFrequency) {
    if (this.muted || !this.gestureSynth) return

    try {
      const frequency = mapColorToFrequency(color)

      if (!frequency) {
        // console.warn('Invalid color for draw sound', color)
        return
      }

      this.gestureSynth.triggerAttackRelease(frequency, '16n', undefined, 0.3)

    } catch (error) {
      // console.warn('Error playing draw sound', error)
    }
  }

  /**
   * Convert note name to MIDI number
   * @param {string} noteName - Note name (e.g., "C3")
   * @returns {number} MIDI note number
   */
  noteNameToMidi(noteName) {
    const noteMap = {
      'C': 0, 'D': 2, 'E': 4, 'F': 5, 'G': 7, 'A': 9, 'B': 11
    }

    const match = noteName.match(/^([A-G])([#b]?)(\d+)$/)
    if (!match) return 60

    const [, note, accidental, octave] = match
    let midiNote = noteMap[note] + (parseInt(octave) + 1) * 12

    if (accidental === '#') midiNote += 1
    if (accidental === 'b') midiNote -= 1

    return midiNote
  }

  /**
   * Convert MIDI note to frequency
   * @param {number} midiNote - MIDI note number
   * @returns {number} Frequency in Hz
   */
  midiToFrequency(midiNote) {
    return 440 * Math.pow(2, (midiNote - 69) / 12)
  }

  /**
   * Build chord from chord name
   * @param {string} chordName - Chord name
   * @returns {number[]} MIDI note numbers
   */
  buildChordFromName(chordName) {
    const noteMap = {
      'C': 60, 'C#': 61, 'Db': 61, 'D': 62, 'D#': 63, 'Eb': 63,
      'E': 64, 'F': 65, 'F#': 66, 'Gb': 66, 'G': 67, 'G#': 68,
      'Ab': 68, 'A': 69, 'A#': 70, 'Bb': 70, 'B': 71
    }

    const rootMatch = chordName.match(/^([A-G][#b]?)/)
    if (!rootMatch) return [60, 64, 67]

    const root = noteMap[rootMatch[1]] || 60

    if (chordName.includes('m')) {
      return [root, root + 3, root + 7]
    } else if (chordName.includes('7')) {
      return [root, root + 4, root + 7, root + 10]
    } else {
      return [root, root + 4, root + 7]
    }
  }

  /**
   * Parse duration string to milliseconds
   * @param {string|number} duration - Duration value
   * @returns {number} Duration in milliseconds
   */
  parseDuration(duration) {
    if (typeof duration === 'number') return duration
    if (typeof duration !== 'string') return 500

    const durationMapMs = {
      '1n': 4000, '2n': 2000, '4n': 1000, '8n': 500, '16n': 250,
      '1m': 60000, '2m': 30000, '4m': 15000
    }

    return durationMapMs[duration] || 500
  }

  /**
   * Stop drone loop
   */
  stopDroneLoop() {
    if (this.droneLoopInterval) {
      clearInterval(this.droneLoopInterval)
      this.droneLoopInterval = null
      // console.log('🛑 Drone loop stopped')
    }
  }

  /**
   * Clear all scheduled timeouts
   */
  clearScheduledTimeouts() {
    this.scheduledTimeouts.forEach(timeoutId => {
      clearTimeout(timeoutId)
    })
    this.scheduledTimeouts = []
  }

  /**
   * Cleanup resources
   */
  cleanup() {
    this.stopDroneLoop()
    this.clearScheduledTimeouts()
    this.ambientLayers = null
    this.gestureSynth = null
  }
}

// Export for browser (window global)
if (typeof window !== 'undefined') {
  window.CompositionPlayer = CompositionPlayer
}

// Export for module systems
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CompositionPlayer
}
